package web;

import com.github.scribejava.core.builder.ServiceBuilder;
import com.github.scribejava.core.model.OAuth1AccessToken;
import com.github.scribejava.core.model.OAuth1RequestToken;
import com.github.scribejava.core.model.OAuthRequest;
import com.github.scribejava.core.model.Response;
import com.github.scribejava.core.model.Verb;
import com.github.scribejava.core.oauth.OAuth10aService;
import core.net.HattrickAPI;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;
import java.io.IOException;
import java.io.OutputStream;
import java.io.StringReader;
import java.net.InetSocketAddress;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import javax.xml.XMLConstants;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.InputSource;

public final class PlayerWebApplicationFixed {
 private static final Map<String,OAuth1RequestToken> REQUEST=new ConcurrentHashMap<>();
 private static final Map<String,OAuth1AccessToken> ACCESS=new ConcurrentHashMap<>();
 private static final String PLAYERS="https://chpp.hattrick.org/chppxml.ashx?file=players&version=1.3&actionType=view&orderBy=PlayerNumber";
 public static void main(String[] a)throws IOException{int port=Integer.parseInt(System.getenv().getOrDefault("PORT","10000"));HttpServer s=HttpServer.create(new InetSocketAddress("0.0.0.0",port),0);s.createContext("/",PlayerWebApplicationFixed::root);s.createContext("/health",e->send(e,200,"OK\n","text/plain; charset=UTF-8"));s.createContext("/oauth/start",PlayerWebApplicationFixed::start);s.createContext("/oauth/callback",PlayerWebApplicationFixed::callback);s.createContext("/players",PlayerWebApplicationFixed::page);s.createContext("/api/players",PlayerWebApplicationFixed::api);s.setExecutor(null);s.start();}
 private static OAuth10aService oauth(){String k=System.getenv("CHPP_CONSUMER_KEY"),sec=System.getenv("CHPP_CONSUMER_SECRET"),cb=System.getenv("CHPP_CALLBACK_URL");if(k==null||sec==null||cb==null)throw new IllegalStateException("CHPP environment variables are missing");return new ServiceBuilder(k).apiSecret(sec).callback(cb).build(HattrickAPI.instance());}
 private static OAuth1AccessToken token(HttpExchange e){String x=cookie(e,"HO_SESSION");return x==null?null:ACCESS.get(x);}
 private static void start(HttpExchange e)throws IOException{try{OAuth10aService o=oauth();OAuth1RequestToken t=o.getRequestToken();String x=UUID.randomUUID().toString();REQUEST.put(x,t);e.getResponseHeaders().add("Set-Cookie","HO_SESSION="+x+"; Path=/; HttpOnly; Secure; SameSite=Lax");redirect(e,o.getAuthorizationUrl(t));}catch(Exception x){send(e,500,"OAuth başlatılamadı: "+x.getMessage(),"text/plain; charset=UTF-8");}}
 private static void callback(HttpExchange e)throws IOException{try{Map<String,String>q=query(e.getRequestURI());String v=q.get("oauth_verifier"),x=cookie(e,"HO_SESSION");OAuth1RequestToken r=x==null?null:REQUEST.remove(x);if(v==null||r==null){send(e,400,"OAuth oturumu geçersiz.","text/plain; charset=UTF-8");return;}ACCESS.put(x,oauth().getAccessToken(r,v));redirect(e,"/players");}catch(Exception x){send(e,500,"OAuth callback hatası: "+x.getMessage(),"text/plain; charset=UTF-8");}}
 private static void root(HttpExchange e)throws IOException{send(e,200,"<html lang='tr'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1'><style>body{font:14px system-ui;margin:0;padding:32px;background:#f5f7fb}main{max-width:720px;margin:auto;background:white;padding:28px;border-radius:16px}a{display:inline-block;padding:10px 14px;background:#1677ff;color:white;text-decoration:none;border-radius:8px}</style></head><body><main><h1>Hattrick Organizer Web</h1><p>CHPP bağlantısı hazır.</p><a href='/players'>Oyuncular / Kadro</a></main></body></html>","text/html; charset=UTF-8");}
 private static void page(HttpExchange e)throws IOException{if(token(e)==null){redirect(e,"/oauth/start");return;}String h="""
 <!doctype html><html lang="tr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HO - Kadro</title><style>
 body{font-family:system-ui,sans-serif;margin:0;padding:18px;background:#f5f7fb;color:#18202a}main{max-width:1400px;margin:auto;background:#fff;padding:18px;border-radius:14px}h1{font-size:22px}.toolbar{display:flex;gap:8px}.toolbar input{flex:1;padding:8px;border:1px solid #ccd3dc;border-radius:8px}.wrap{overflow:auto}.status{font-size:12px;color:#667085;margin:7px 0}table{border-collapse:collapse;width:100%;font-size:11px;white-space:nowrap}th,td{padding:5px 7px;border-bottom:1px solid #e7e9ee;text-align:left}th{background:#f0f3f7}.num{text-align:right}.bad{color:#b42318;font-weight:600}.ok{color:#027a48}
 </style></head><body><main><h1>Oyuncular / Kadro</h1><div class="toolbar"><input id="q" placeholder="Oyuncu ara..."><span id="count" class="status"></span></div><div id="status" class="status">CHPP'den kadro alınıyor...</div><div class="wrap"><table><thead><tr><th>#</th><th>Oyuncu</th><th>Yaş</th><th>TSI</th><th>Form</th><th>Kond.</th><th>GK</th><th>DEF</th><th>PM</th><th>PAS</th><th>KAN</th><th>GOL</th><th>SP</th><th>Tecr.</th><th>Lid.</th><th>Maaş</th><th>Uzmanlık</th><th>Sak.</th><th>Kart</th><th>Transfer</th></tr></thead><tbody id="players"></tbody></table></div></main><script>
 const q=document.getElementById('q'),body=document.getElementById('players'),status=document.getElementById('status'),count=document.getElementById('count');let data=[];q.oninput=render;fetch('/api/players').then(async r=>{const t=await r.text();let x;try{x=JSON.parse(t)}catch(e){throw new Error('Geçersiz JSON: '+t.slice(0,160))}if(!r.ok)throw new Error(x.error||'Hata');return x}).then(x=>{data=x.players||[];status.textContent='Kadro yüklendi';status.className='status ok';render()}).catch(e=>{status.textContent=e.message;status.className='status bad'});function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function render(){let s=q.value.toLowerCase(),rows=data.filter(p=>(p.name||'').toLowerCase().includes(s));count.textContent=rows.length+' / '+data.length;body.innerHTML=rows.map(p=>`<tr><td class=num>${esc(p.number)}</td><td><b>${esc(p.name)}</b></td><td>${esc(p.age)}/${esc(p.ageDays)}</td><td class=num>${esc(p.tsi)}</td><td class=num>${esc(p.form)}</td><td class=num>${esc(p.stamina)}</td><td class=num>${esc(p.keeper)}</td><td class=num>${esc(p.defender)}</td><td class=num>${esc(p.playmaker)}</td><td class=num>${esc(p.passing)}</td><td class=num>${esc(p.winger)}</td><td class=num>${esc(p.scorer)}</td><td class=num>${esc(p.setPieces)}</td><td class=num>${esc(p.experience)}</td><td class=num>${esc(p.leadership)}</td><td class=num>${esc(p.salary)}</td><td>${esc(p.specialty)}</td><td class=num>${esc(p.injuryLevel)}</td><td class=num>${esc(p.cards)}</td><td>${p.transferListed==='1'?'Evet':''}</td></tr>`).join('')}
 </script></body></html>
 """;send(e,200,h,"text/html; charset=UTF-8");}
 private static void api(HttpExchange e)throws IOException{try{OAuth1AccessToken t=token(e);if(t==null){send(e,401,"{\"error\":\"CHPP bağlantısı yok\"}","application/json; charset=UTF-8");return;}OAuthRequest r=new OAuthRequest(Verb.GET,PLAYERS);OAuth10aService o=oauth();o.signRequest(t,r);Response z=o.execute(r);if(!z.isSuccessful()){send(e,502,"{\"error\":"+js("CHPP API HTTP "+z.getCode())+"}","application/json; charset=UTF-8");return;}Document d=xml(z.getBody());NodeList n=d.getElementsByTagName("Player");StringBuilder b=new StringBuilder("{\"players\":[");for(int i=0;i<n.getLength();i++){if(i>0)b.append(',');Element p=(Element)n.item(i);b.append('{');f(b,"id",c(p,"PlayerID"));f(b,"name",c(p,"PlayerName"));f(b,"number",c(p,"PlayerNumber"));f(b,"age",c(p,"Age"));f(b,"ageDays",c(p,"AgeDays"));f(b,"tsi",c(p,"TSI"));f(b,"form",c(p,"PlayerForm"));f(b,"stamina",c(p,"StaminaSkill"));f(b,"keeper",c(p,"KeeperSkill"));f(b,"defender",c(p,"DefenderSkill"));f(b,"playmaker",c(p,"PlaymakerSkill"));f(b,"passing",c(p,"PassingSkill"));f(b,"winger",c(p,"WingerSkill"));f(b,"scorer",c(p,"ScorerSkill"));f(b,"setPieces",c(p,"SetPiecesSkill"));f(b,"experience",c(p,"Experience"));f(b,"leadership",c(p,"Leadership"));f(b,"salary",c(p,"Salary"));f(b,"specialty",spec(c(p,"Specialty")));f(b,"injuryLevel",c(p,"InjuryLevel"));f(b,"cards",c(p,"Cards"));fl(b,"transferListed",c(p,"TransferListed"));b.append('}');}b.append("]}");send(e,200,b.toString(),"application/json; charset=UTF-8");}catch(Exception x){x.printStackTrace();send(e,502,"{\"error\":"+js("Kadro alınamadı: "+x.getMessage())+"}","application/json; charset=UTF-8");}}
 private static void f(StringBuilder b,String k,String v){b.append(js(k)).append(':').append(js(v)).append(',');}private static void fl(StringBuilder b,String k,String v){b.append(js(k)).append(':').append(js(v));}
 private static String js(String v){if(v==null)v="";StringBuilder b=new StringBuilder("\"");for(char c:v.toCharArray()){switch(c){case '"'->b.append("\\\"");case '\\'->b.append("\\\\");case '\b'->b.append("\\b");case '\f'->b.append("\\f");case '\n'->b.append("\\n");case '\r'->b.append("\\r");case '\t'->b.append("\\t");default->b.append(c);}}return b.append('"').toString();}
 private static Document xml(String x)throws Exception{DocumentBuilderFactory f=DocumentBuilderFactory.newInstance();f.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING,true);f.setFeature("http://apache.org/xml/features/disallow-doctype-decl",true);f.setFeature("http://xml.org/sax/features/external-general-entities",false);f.setFeature("http://xml.org/sax/features/external-parameter-entities",false);f.setXIncludeAware(false);f.setExpandEntityReferences(false);return f.newDocumentBuilder().parse(new InputSource(new StringReader(x)));}
 private static String c(Element p,String tag){NodeList n=p.getElementsByTagName(tag);return n.getLength()==0?"":n.item(0).getTextContent();}private static String spec(String v){return switch(v){case"1"->"Teknik";case"2"->"Hızlı";case"3"->"Güçlü";case"4"->"Öngörülemez";case"5"->"Kafa uzmanı";default->v==null?"":v;};}
 private static Map<String,String> query(URI u){Map<String,String>m=new HashMap<>();String x=u.getRawQuery();if(x==null)return m;for(String p:x.split("&")){String[]a=p.split("=",2);m.put(java.net.URLDecoder.decode(a[0],StandardCharsets.UTF_8),a.length>1?java.net.URLDecoder.decode(a[1],StandardCharsets.UTF_8):"");}return m;}
 private static String cookie(HttpExchange e,String name){String h=e.getRequestHeaders().getFirst("Cookie");if(h==null)return null;for(String p:h.split(";")){String[]a=p.trim().split("=",2);if(a.length==2&&a[0].equals(name))return a[1];}return null;}private static void redirect(HttpExchange e,String x)throws IOException{e.getResponseHeaders().set("Location",x);e.sendResponseHeaders(302,-1);e.close();}private static void send(HttpExchange e,int s,String b,String ct)throws IOException{byte[]x=b.getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().set("Content-Type",ct);e.sendResponseHeaders(s,x.length);try(OutputStream o=e.getResponseBody()){o.write(x);}}
}
